### ISSUE TITLE
Build fails with lib missing error

### ISSUE THREAD

**Issue by fmaussion** [OGGM/r2d#13]
@TimoRoth if you have a minute to check this: https://github.com/OGGM/r2d/runs/6840943325?check_suite_focus=true#step:6:2302 

```
ImportError: libcrypto.so.1.1: cannot open shared object file: No such file or directory
```

**Comment by fmaussion** [comment]
seems to have magically resolved itself

**Comment by TimoRoth** [comment]
Ah, yeah.
It must have built right in the middle of me updating the images, so the first stage was Ubuntu 22.04, while the second was still 20.04.
