### ISSUE TITLE
Add CI tests?

### ISSUE THREAD

**Issue by fmaussion** [OGGM/r2d#2]
@TimoRoth - as discussed on slack, it might be worthwhile adding tests to the travis script - not sure how that would work though: it should not contaminate the repo's HOME before push.

**Comment by TimoRoth** [comment]
Not sure what you mean by contaminating the repos HOME.
But also not sure how to test the image. You mean run the normal OGGM tests in it?

**Comment by fmaussion** [comment]
> You mean run the normal OGGM tests in it?

Yes

> Not sure what you mean by contaminating the repos HOME.

I mean the image's HOME: salem and oggm have the bad habit of caching things in home, and I wouldn't want the tests to do this. 

So maybe the solution would be:
- build the image
- copy it and test the copy
- push the original one?

**Comment by TimoRoth** [comment]
It's a Docker image. Starting a container and running stuff in it won't alter the image in any way.
Running the OGGM tests in it should be a single pytest command.

**Comment by fmaussion** [comment]
> It's a Docker image. Starting a container and running stuff in it won't alter the image in any way.

Right, for some reason if was thinking that the tests need to be run in the image build script but this can be done afterwards. Mind adding this to travis?

While you are at it, I think I would like to add a git commit hash to the daily tag for a while - something like: `DATE-comit_hash`

**Comment by TimoRoth** [comment]
I figured that including a commit hash of this repo wouldn't be overly informative, given that once everything is setup, it'll barely ever change at all?

**Comment by fmaussion** [comment]
yes, but currently I'm still changing a lot (unfortunately). See e.g. https://discourse.jupyter.org/t/users-home-in-jupyterhub/1463 

but yeah, don't bother for now

**Comment by fmaussion** [comment]
@TimoRoth could you run all OGGM tests im .travis.yml here?
